"""Kullanici tablosuna email eklendi

Revision ID: 2187d79f1c14
Revises: a66a1aecf76f
Create Date: 2026-10-01 17:47:28.368924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2187d79f1c14'
down_revision = 'a66a1aecf76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), server_default='mailsiz@mailsiz.mailsiz', nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_kullanici_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kullanici', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_kullanici_email'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
