"""Kullanici tablosu

Revision ID: a66a1aecf76f
Revises: 
Create Date: 2026-10-01 16:48:31.614433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66a1aecf76f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('kayit_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici')
    # ### end Alembic commands ###
